# -*- coding: utf-8 -*-
"""dashboard_e-commerce.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1X2KWEcZiE6_2ELZBlGiyYNU3xRC64ON6

# Proyek Analisis Data: E-Commerce Public Dataset
- **Nama:** Nurya Fahru Rosyidin
- **Email:** nurya.fahrurosyidin@gmail.com
- **ID Dicoding:** nuryafahrurosyidin

## Menentukan Pertanyaan Bisnis

- Pertanyaan 1 : Bagaimana tren total order dan total revenue (pendapatan) perusahaan setiap bulannya selama tahun terakhir yang tersedia dalam data?
- Pertanyaan 2 : Berapa rata-rata skor ulasan pelanggan untuk setiap kategori produk, dan kategori mana yang memiliki tingkat kepuasan terendah?
- Pertanyaan 3 : Di negara bagian mana pelanggan terbanyak berada, dan apakah wilayah tersebut berkontribusi paling besar terhadap total penjualan?
- Pertanyaan 4 : 10 kategori produk apa yang menghasilkan nilai transaksi tertinggi dan apakah kategori tersebut juga merupakan kategori dengan jumlah item terjual terbanyak?

## Import Semua Packages/Library yang Digunakan
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

"""## Data Wrangling

### Gathering Data

#### 1. Customers Dataset
"""

customers_df = pd.read_csv("/content/drive/MyDrive/Colab_Notebooks/Dataset/data_dicoding_e-commerce/customers_dataset.csv")
customers_df.head()

"""#### 2. Geolocation Dataset"""

geolocation_df = pd.read_csv("/content/drive/MyDrive/Colab_Notebooks/Dataset/data_dicoding_e-commerce/geolocation_dataset.csv")
geolocation_df.head()

"""#### 3. Order Items Dataset"""

order_items_df = pd.read_csv("/content/drive/MyDrive/Colab_Notebooks/Dataset/data_dicoding_e-commerce/order_items_dataset.csv")
order_items_df.head()

"""#### 4. Order Payments Dataset"""

order_payments_df = pd.read_csv("/content/drive/MyDrive/Colab_Notebooks/Dataset/data_dicoding_e-commerce/order_payments_dataset.csv")
order_payments_df.head()

"""#### 5. Order Reviews Dataset"""

order_reviews_df = pd.read_csv("/content/drive/MyDrive/Colab_Notebooks/Dataset/data_dicoding_e-commerce/order_reviews_dataset.csv")
order_reviews_df.head()

"""#### 6. Orders Dataset"""

orders_df = pd.read_csv("/content/drive/MyDrive/Colab_Notebooks/Dataset/data_dicoding_e-commerce/orders_dataset.csv")
orders_df.head()

"""#### 7. Product Category Name Translation Dataset"""

product_category_name_translation_df = pd.read_csv("/content/drive/MyDrive/Colab_Notebooks/Dataset/data_dicoding_e-commerce/product_category_name_translation.csv")
product_category_name_translation_df.head()

"""#### 8. Products Dataset"""

products_df = pd.read_csv("/content/drive/MyDrive/Colab_Notebooks/Dataset/data_dicoding_e-commerce/products_dataset.csv")
products_df.head()

"""#### 9. Sellers Dataset"""

sellers_df = pd.read_csv("/content/drive/MyDrive/Colab_Notebooks/Dataset/data_dicoding_e-commerce/sellers_dataset.csv")
sellers_df.head()

"""#### nama-nama variabel yang digunakan untuk menyimpan dataset:
1. customers_df : dataset customers
2. geolocation_df : dataset geolocation
3. order_items_df : dataset order items
4. order_payments_df : dataset order payments
5. order_reviews_df : dataset order reviews
6. orders_df : dataset orders
7. product_category_name_translation_df : dataset product category name translation
8. products_df : dataset products
9. sellers_df : dataset sellers

Juga rincian isi dari dataset:
1. customers_dataset.csv berisi customer_id,"customer_unique_id","customer_zip_code_prefix","customer_city","customer_state"

2. geolocation_dataset.csv berisi geolocation_zip_code_prefix,"geolocation_lat","geolocation_lng","geolocation_city","geolocation_state"

3. order_items_dataset.csv berisi order_id,"order_item_id","product_id","seller_id","shipping_limit_date","price","freight_value"

4. order_payments_dataset.csv berisi order_id,"payment_sequential","payment_type","payment_installments","payment_value"

5. order_reviews_dataset.csv berisi review_id,"order_id","review_score","review_comment_title","review_comment_message","review_creation_date","review_answer_timestamp"

6. orders_dataset.csv berisi order_id,"customer_id","order_status","order_purchase_timestamp","order_approved_at","order_delivered_carrier_date","order_delivered_customer_date","order_estimated_delivery_date"

7. product_category_name_translation.csv berisi product_category_name,product_category_name_english

8. products_dataset.csv berisi product_id,"product_category_name","product_name_lenght","product_description_lenght","product_photos_qty","product_weight_g","product_length_cm","product_height_cm","product_width_cm"

9. sellers_dataset.csv berisi seller_id,"seller_zip_code_prefix","seller_city","seller_state"

### Assessing Data

#### 1. Menilai tabel `customers_df`
"""

# Cek tipe data
print("Cek Informasi dan Tipe Data")
customers_df.info()

# Cek missing value
print("Cek Missing Value")
customers_df.isna().sum()

# Cek jumlah duplikat
print("Cek Jumlah Duplikat: ", customers_df.duplicated().sum())

# Cek inaccurate value
print("Cek Inaccurate Value")
customers_df.describe()

"""#### 2. Menilai tabel `geolocation_df`"""

# Cek tipe data
print("Cek Informasi dan Tipe Data")
geolocation_df.info()

# Cek missing value
print("Cek Missing Value")
geolocation_df.isna().sum()

# Cek jumlah duplikat
print("Cek Jumlah Duplikat: ", geolocation_df.duplicated().sum())

# Cek inaccurate value
print("Cek Inaccurate Value")
geolocation_df.describe()

"""#### 3. Menilai tabel `order_items_df`"""

# Cek tipe data
print("Cek Informasi dan Tipe Data")
order_items_df.info()

# Cek missing value
print("Cek Missing Value")
order_items_df.isna().sum()

# Cek jumlah duplikat
print("Cek Jumlah Duplikat: ", order_items_df.duplicated().sum())

# Cek inaccurate value
print("Cek Inaccurate Value")
order_items_df.describe()

"""#### 4. Menilai tabel `order_payments_df`"""

# Cek tipe data
print("Cek Informasi dan Tipe Data")
order_payments_df.info()

# Cek missing value
print("Cek Missing Value")
order_payments_df.isna().sum()

# Cek jumlah duplikat
print("Cek Jumlah Duplikat: ", order_payments_df.duplicated().sum())

# Cek inaccurate value
print("Cek Inaccurate Value")
order_payments_df.describe()

"""#### 5. Menilai tabel  `order_reviews_df`"""

# Cek tipe data
print("Cek Informasi dan Tipe Data")
order_reviews_df.info()

# Cek missing value
print("Cek Missing Value")
order_reviews_df.isna().sum()

# Cek jumlah duplikat
print("Cek Jumlah Duplikat: ", order_reviews_df.duplicated().sum())

# Cek inaccurate value
print("Cek Inaccurate Value")
order_reviews_df.describe()

"""#### 6. Menilai tabel `orders_df`"""

# Cek tipe data
print("Cek Informasi dan Tipe Data")
orders_df.info()

# Cek missing value
print("Cek Missing Value")
orders_df.isna().sum()

# Cek jumlah duplikat
print("Cek Jumlah Duplikat: ", orders_df.duplicated().sum())

# Cek inaccurate value
print("Cek Inaccurate Value")
orders_df.describe()

"""#### 7. Menilai tabel `product_category_name_translation_df`"""

# Cek tipe data
print("Cek Informasi dan Tipe Data")
product_category_name_translation_df.info()

# Cek missing value
print("Cek Missing Value")
product_category_name_translation_df.isna().sum()

# Cek jumlah duplikat
print("Cek Jumlah Duplikat: ", product_category_name_translation_df.duplicated().sum())

# Cek inaccurate value
print("Cek Inaccurate Value")
product_category_name_translation_df.describe()

"""#### 8. Menilai tabel `products_df`"""

# Cek tipe data
print("Cek Informasi dan Tipe Data")
products_df.info()

# Cek missing value
print("Cek Missing Value")
products_df.isna().sum()

# Cek jumlah duplikat
print("Cek Jumlah Duplikat: ", products_df.duplicated().sum())

# Cek inaccurate value
print("Cek Inaccurate Value")
products_df.describe()

"""#### 9. Menilai tabel `sellers_df`"""

# Cek tipe data
print("Cek Informasi dan Tipe Data")
sellers_df.info()

# Cek missing value
print("Cek Missing Value")
sellers_df.isna().sum()

# Cek jumlah duplikat
print("Cek Jumlah Duplikat: ", sellers_df.duplicated().sum())

# Cek inaccurate value
print("Cek Inaccurate Value")
sellers_df.describe()

"""Berikut ini adalah tabel dari Assessing Data pada dataset.

|   | Tipe Data | Missing Value | Duplicate Data | Inaccurate Value |
| --- | --- | --- | --- | --- |
| 1. customers_df | - | - | - | - |
| 2. geolocation_df | - | - | Terdapat 261831 data yang duplikat | - |
| 3. order_items_df | Terdapat kesalahan tipe data untuk kolom shipping_limit_date | - | - | - |
| 4. order_payments_df | - | - | - | - |
| 5. order_reviews_df | Terdapat kesalahan tipe data untuk kolom review_creation_date dan review_answer_timestamp | Terdapat missing value pada kolom review_comment_title dan review_comment_message | - | - |
| 6. orders_df | Terdapat kesalahan tipe data pada kolom order_purchase_timestamp, order_delivered_carrier_date, order_delivered_customer_date, dan order_estimated_delivery_date | Terdapat missing value pada kolom order_approved_at, order_delivered_carrier_date, dan order_delivered_customer_date | - | - |
| 7. product_category_name_translation_df | - | - | - | - |
| 8. products_df | - | Terdapat banyak kolom yang missing value | - | - |
| 9. sellers_df | - | - | - | - |

### Cleaning Data

#### 1. Membersihkan tabel `geolocation_df`

##### Duplicate Data
"""

geolocation_df.duplicated().sum()

geolocation_df.drop_duplicates(inplace=True)

print("Cek Jumlah Duplikat: ", geolocation_df.duplicated().sum())

"""#### 2. Membersihkan tabel `order_items_df`

##### Memperbaiki tipe data
"""

order_items_df.info()

datetime_columns = ["shipping_limit_date"]
for column in datetime_columns:
  order_items_df[column] = pd.to_datetime(order_items_df[column])

order_items_df.info()

"""#### 3. Membersihkan tabel `order_reviews_df`

##### Memperbaiki tipe data
"""

order_reviews_df.info()

datetime_columns = ["review_creation_date", "review_answer_timestamp"]
for column in datetime_columns:
  order_reviews_df[column] = pd.to_datetime(order_reviews_df[column])

order_reviews_df.info()

"""##### Memperbaiki missing value"""

order_reviews_df.isna().sum()

order_reviews_df[order_reviews_df["review_comment_title"].isna()]

order_reviews_df[order_reviews_df["review_comment_message"].isna()]

order_reviews_df['review_comment_title'] = order_reviews_df['review_comment_title'].fillna("-")
order_reviews_df['review_comment_message'] = order_reviews_df['review_comment_message'].fillna("-")

order_reviews_df

order_reviews_df.isna().sum()

"""#### 4. Membersihkan tabel `orders_df`

##### Memperbaiki tipe data
"""

orders_df.info()

datetime_columns = ["order_purchase_timestamp", "order_delivered_carrier_date", "order_delivered_customer_date", "order_estimated_delivery_date"]
for column in datetime_columns:
  orders_df[column] = pd.to_datetime(orders_df[column])

orders_df.info()

"""##### Memperbaiki missing value"""

orders_df.isna().sum()

orders_df[orders_df["order_approved_at"].isna()]

orders_df[orders_df["order_delivered_carrier_date"].isna()]

orders_df[orders_df["order_delivered_customer_date"].isna()]

orders_df['order_approved_at'] = orders_df['order_approved_at'].fillna("-")
orders_df['order_delivered_carrier_date'] = orders_df['order_delivered_carrier_date'].fillna("-")
orders_df['order_delivered_customer_date'] = orders_df['order_delivered_customer_date'].fillna("-")

orders_df

orders_df.isna().sum()

"""#### 5. Membersihkan tabel `products_df`

##### Memperbaiki missing value
"""

products_df.isna().sum()

products_df[products_df["product_category_name"].isna()]

products_df[products_df["product_name_lenght"].isna()]

products_df[products_df["product_description_lenght"].isna()]

products_df[products_df["product_photos_qty"].isna()]

products_df[products_df["product_weight_g"].isna()]

products_df[products_df["product_length_cm"].isna()]

products_df[products_df["product_height_cm"].isna()]

products_df[products_df["product_width_cm"].isna()]

products_df['product_category_name'] = products_df['product_category_name'].fillna("-")
products_df.dropna(subset=['product_name_lenght'], inplace=True)
products_df.dropna(subset=['product_description_lenght'], inplace=True)
products_df.dropna(subset=['product_photos_qty'], inplace=True)
products_df.dropna(subset=['product_weight_g'], inplace=True)
products_df.dropna(subset=['product_length_cm'], inplace=True)
products_df.dropna(subset=['product_height_cm'], inplace=True)
products_df.dropna(subset=['product_width_cm'], inplace=True)

products_df.isna().sum()

products_df.info()

"""Berikut ini adalah tabel dari Cleaning Data pada dataset yang sudah dilakukan.

|   | Tipe Data | Missing Value | Duplicate Data | Inaccurate Value |
| --- | --- | --- | --- | --- |
| 1. customers_df | - | - | - | - |
| 2. geolocation_df (Sudah Clear) | - | - | Terdapat 261831 data yang duplikat | - |
| 3. order_items_df (Sudah Clear) | Terdapat kesalahan tipe data untuk kolom shipping_limit_date | - | - | - |
| 4. order_payments_df | - | - | - | - |
| 5. order_reviews_df (Sudah Clear) | Terdapat kesalahan tipe data untuk kolom review_creation_date dan review_answer_timestamp | Terdapat missing value pada kolom review_comment_title dan review_comment_message | - | - |
| 6. orders_df (Sudah Clear) | Terdapat kesalahan tipe data pada kolom order_purchase_timestamp, order_delivered_carrier_date, order_delivered_customer_date, dan order_estimated_delivery_date | Terdapat missing value pada kolom order_approved_at, order_delivered_carrier_date, dan order_delivered_customer_date | - | - |
| 7. product_category_name_translation_df | - | - | - | - |
| 8. products_df (Sudah Clear) | - | Terdapat banyak kolom yang missing value | - | - |
| 9. sellers_df | - | - | - | - |

## Exploratory Data Analysis (EDA)

Berikut adalah pertanyaan-pertanyaan bisnis yang sudah dibuat sebelumnya:
- Pertanyaan 1 : Bagaimana tren total order dan total revenue (pendapatan) perusahaan setiap bulannya selama tahun terakhir yang tersedia dalam data?
- Pertanyaan 2 : Berapa rata-rata skor ulasan pelanggan untuk setiap kategori produk, dan kategori mana yang memiliki tingkat kepuasan terendah?
- Pertanyaan 3 : Di negara bagian mana pelanggan terbanyak berada, dan apakah wilayah tersebut berkontribusi paling besar terhadap total penjualan?
- Pertanyaan 4 : 10 kategori produk apa yang menghasilkan nilai transaksi tertinggi dan apakah kategori tersebut juga merupakan kategori dengan jumlah item terjual terbanyak?

### 1. Explore `customers_df`
"""

customers_df.sample(5)

customers_df.describe(include="all")

customers_df.groupby(by="customer_city").customer_id.nunique().sort_values(ascending=False)

customers_df.groupby(by="customer_state").customer_id.nunique().sort_values(ascending=False)

"""### 2. Explore `geolocation_df`"""

geolocation_df.sample(5)

geolocation_df.describe(include="all")

geolocation_df.groupby(by="geolocation_city").geolocation_zip_code_prefix.nunique().sort_values(ascending=False)

geolocation_df.groupby(by="geolocation_state").geolocation_zip_code_prefix.nunique().sort_values(ascending=False)

"""### 3. Explore `order_items_df`"""

order_items_df.sample(5)

order_items_df.describe(include="all")

print(order_items_df.max())

"""### 4. Explore `order_payments_df`"""

order_payments_df.sample(5)

order_payments_df.describe(include="all")

order_payments_df.groupby(by="payment_type").payment_value.sum().sort_values(ascending=False)

"""### 5. Explore `order_reviews_df`"""

order_reviews_df.sample(5)

order_reviews_df.describe(include="all")

order_reviews_df.groupby(by="review_score").review_id.nunique().sort_values(ascending=False)

"""### 6. Explore `orders_df`"""

orders_df.sample(5)

orders_df.describe(include="all")

orders_df.groupby(by="order_status").order_id.nunique().sort_values(ascending=False)

"""### 7. Explore `product_category_name_translation_df`"""

product_category_name_translation_df.sample(5)

product_category_name_translation_df.describe(include="all")

"""### 8. Explore `products_df`"""

products_df.sample(5)

products_df.describe(include="all")

"""### 9. Explore `sellers_df`"""

sellers_df.sample(5)

sellers_df.describe(include="all")

sellers_df.groupby(by="seller_city").seller_id.nunique().sort_values(ascending=False)

sellers_df.groupby(by="seller_state").seller_id.nunique().sort_values(ascending=False)

"""### Menjawab pertanyaan

### Pertanyaan 1 : Bagaimana tren total order dan total revenue (pendapatan) perusahaan setiap bulannya selama tahun terakhir yang tersedia dalam data?

#### Explore `orders_df` dan `order_items_df`

##### Menggabungkan `orders_df` dan `order_items_df`
"""

order_revenue_df = pd.merge(
    left=orders_df,
    right=order_items_df,
    how="inner",
    on="order_id"
)
order_revenue_df.head()

order_revenue_df['order_month'] = order_revenue_df['order_purchase_timestamp'].dt.to_period('M')
order_revenue_df.head()

monthly_revenue_df = order_revenue_df.groupby(by="order_month").agg({
    "order_id": "nunique",
    "price": "sum"
}).reset_index()
monthly_revenue_df

monthly_revenue_df.rename(columns={
    "order_id" : "total_orders",
    "price" : "total_revenue"
}, inplace=True)
monthly_revenue_df

last_date = order_revenue_df["order_purchase_timestamp"].max()
start_date = last_date - pd.DateOffset(months=12)
monthly_revenue_last_year = monthly_revenue_df[monthly_revenue_df['order_month'] >= start_date.to_period('M')]
print(monthly_revenue_last_year)

"""### Pertanyaan 2 : Berapa rata-rata skor ulasan pelanggan untuk setiap kategori produk, dan kategori mana yang memiliki tingkat kepuasan terendah?

#### Explore `order_reviews_df`, `order_items_df`, `products_df`, dan `product_category_name_translation_df`

##### Menggabungkan `order_reviews_df`, `order_items_df`, `products_df`, dan `product_category_name_translation_df`
"""

items_product_df = pd.merge(
    left=order_items_df,
    right=products_df,
    how="left",
    on="product_id"
)
items_product_df.head()

product_review_df = pd.merge(
    left=items_product_df,
    right=order_reviews_df,
    how="left",
    on="order_id"
)
product_review_df.head()

final_product_review_df = pd.merge(
    left=product_review_df,
    right=product_category_name_translation_df,
    how="left",
    on="product_category_name"
)
final_product_review_df.head()

category_review_stats = final_product_review_df.groupby(by="product_category_name_english").agg({
    "review_score": "mean",
    "order_id": "count"
}).reset_index()
category_review_stats

category_review_stats = category_review_stats.sort_values(by="review_score", ascending=True)
print(category_review_stats.head(10))

"""### Pertanyaan 3 : Di negara bagian mana pelanggan terbanyak berada, dan apakah wilayah tersebut berkontribusi paling besar terhadap total penjualan?

#### Explore `customers_df`, `order_items_df`, dan `orders_df`
"""

print(customers_df.head())
print(customers_df['customer_state'].value_counts().head(10))

print(orders_df[['order_id', 'customer_id']].head())

"""##### Menggabungkan `customers_df`, `orders_df` dan `order_items_df`"""

customers_orders_df = pd.merge(
    left=customers_df,
    right=orders_df,
    how="inner",
    on="customer_id"
)
customers_orders_df.head()

customers_sales_df = pd.merge(
    left=customers_orders_df,
    right=order_items_df,
    how="inner",
    on="order_id"
)
customers_sales_df.head()

state_analysis_df = customers_sales_df.groupby(by="customer_state").agg({
    "customer_unique_id": "nunique",
    "price": "sum"
}).reset_index()
state_analysis_df

state_analysis_df = state_analysis_df.sort_values(by="customer_unique_id", ascending=False)
state_analysis_df

total_revenue_all = state_analysis_df["price"].sum()
state_analysis_df["revenue_percentage"] = (state_analysis_df["price"] / total_revenue_all) * 100
state_analysis_df

print(state_analysis_df.head(10))

"""### Pertanyaan 4 : 10 kategori produk apa yang menghasilkan nilai transaksi tertinggi dan apakah kategori tersebut juga merupakan kategori dengan jumlah item terjual terbanyak?

#### Explore `order_items_df`, `products_df`, dan `product_category_name_translation_df`

##### Menggabungkan `order_items_df`, `products_df`, dan `product_category_name_translation_df`
"""

product_performance_df = pd.merge(
    left=order_items_df,
    right=products_df,
    how="left",
    on="product_id"
)
product_performance_df

product_performance_df = pd.merge(
    left=product_performance_df,
    right=product_category_name_translation_df,
    how="left",
    on="product_category_name"
)
product_performance_df

category_analysis = product_performance_df.groupby(by="product_category_name_english").agg({
    "price": "sum",
    "order_item_id": "count"
}).reset_index()
category_analysis

category_analysis.rename(columns={
    "price": "total_revenue",
    "order_item_id": "total_items_sold"
}, inplace=True)
category_analysis

top_10_revenue = category_analysis.sort_values(by="total_revenue", ascending=False).head(10)
print("10 kategori produk yang menghasilkan nilai transaksi tertinggi:")
print(top_10_revenue)

"""### Penggabungan semua dataset menjadi satu dataset"""

all_df = pd.merge(
    left=orders_df,
    right=order_items_df,
    how="left",
    on="order_id"
)

all_df = pd.merge(
    left=all_df,
    right=order_payments_df,
    how="left",
    on="order_id"
)

all_df = pd.merge(
    left=all_df,
    right=order_reviews_df,
    how="left",
    on="order_id"
)

all_df = pd.merge(
    left=all_df,
    right=customers_df,
    how="left",
    on="customer_id"
)

all_df = pd.merge(
    left=all_df,
    right=products_df,
    how="left",
    on="product_id"
)

all_df = pd.merge(
    left=all_df,
    right=sellers_df,
    how="left",
    on="seller_id"
)

all_df = pd.merge(
    left=all_df,
    right=product_category_name_translation_df,
    how="left",
    on="product_category_name"
)

all_df.head(10)

all_df.to_csv("all_data.csv", index=False)

"""## Visualization & Explanatory Analysis

### Pertanyaan 1: Bagaimana tren total order dan total revenue (pendapatan) perusahaan setiap bulannya selama tahun terakhir yang tersedia dalam data?
"""

print(monthly_revenue_last_year)

monthly_revenue_last_year['order_month_str'] = monthly_revenue_last_year['order_month'].astype(str)

fig, ax = plt.subplots(nrows=2, ncols=1, figsize=(12, 10))

# Untuk plot total orders
sns.lineplot(
    x="order_month_str",
    y="total_orders",
    data=monthly_revenue_last_year,
    marker="o",
    linewidth=2,
    color="#72BCD4",
    ax=ax[0]
)
ax[0].set_title("Total Order per Bulan (Akhir Tahun)", loc="center", fontsize=15)
ax[0].set_ylabel("Total Order")
ax[0].set_xlabel(None)
ax[0].tick_params(axis='x', rotation=45)

#Untuk plot total revenue
sns.lineplot(
    x="order_month_str",
    y="total_revenue",
    data=monthly_revenue_last_year,
    marker="o",
    linewidth=2,
    color="#90CAF9",
    ax=ax[1]
)
ax[1].set_title("Total Revenue per Bulan (Akhir Tahun)", loc="center", fontsize=15)
ax[1].set_ylabel("Total Revenue (dalam juta)")
ax[1].set_xlabel("Bulan")
ax[1].tick_params(axis='x', rotation=45)

plt.tight_layout()
plt.show()

"""Berdasarkan pada visualisasi tersebut tersebut, performa perusahaan mencapai puncaknya pada bulan November tahun 2017 dengan `total_revenue` dan `total_order` tertinggi yang mengindikasikan keberhasilan strategi promosi (efek diskon hari besar). Jika pendapatan naik tajam di bulan tersebut, berarti strategi promosi musiman perusahaan sangat efektif.

### Pertanyaan 2: Berapa rata-rata skor ulasan pelanggan untuk setiap kategori produk, dan kategori mana yang memiliki tingkat kepuasan terendah?
"""

print(category_review_stats)

# 10 Product Categories with the Lowest Review Scores
low_score_categories = category_review_stats.sort_values(by="review_score", ascending=True).head(10)
# low_score_categories

plt.figure(figsize=(12, 6))
sns.barplot(
    x="review_score",
    y="product_category_name_english",
    data=low_score_categories,
    palette="Reds_r"
)

plt.title("10 Kategori Produk dengan Skor Ulasan Terendah", loc="center", fontsize=15)
plt.xlabel("Rata-Rata Skor Ulasan")
plt.ylabel("Kategori Produk")
plt.xlim(0, 5)
plt.show()

"""Berdasarkan dari hasil visualisasi berikut, kategori security_and_services memiliki tingkat kepuasan terendah dengan rata-rata skor hanya 2,5. Hal ini mungkin terjadi karena ada masalah pada kualitas barang atau keterlambatan pengiriman.

### Pertanyaan 3: Di negara bagian mana pelanggan terbanyak berada, dan apakah wilayah tersebut berkontribusi paling besar terhadap total penjualan?
"""

print(state_analysis_df)

top_10_states = state_analysis_df.sort_values(by="customer_unique_id", ascending=False).head(10)

fig, ax = plt.subplots(nrows=1, ncols=2, figsize=(15, 6))

#Untuk plot jumlah pelanggan
sns.barplot(
    x="customer_unique_id",
    y="customer_state",
    data=top_10_states,
    palette="Blues_r",
    ax=ax[0]
)
ax[0].set_title("10 Negara Bagian Teratas Berdasarkan Jumlah Pelanggan", loc="center", fontsize=15)
ax[0].set_xlabel("Pelanggan")
ax[0].set_ylabel(None)

#Untuk total penjualan
sns.barplot(
    x="price",
    y="customer_state",
    data=top_10_states,
    palette="Greens_r",
    ax=ax[1]
)
ax[1].set_title("10 Negara Bagian Teratas Berdasarkan Total Penjualan", loc="center", fontsize=15)
ax[1].set_xlabel("Total Revenue")
ax[1].set_ylabel(None)

plt.tight_layout()
plt.show()

"""Berdasarkan dari hasil visualisasi berikut didapatkan bahwa SP (Sao Paulo) menjadi negara bagian yang mendapatkan jumlah pelanggan terbanyak yaitu 39.981 pelanggan dan juga wilayah yang berkontribusi besar terhadap total penjualan dengan 38,28% dari total revenue keseluruhan.

### Pertanyaan 4: 10 kategori produk apa yang menghasilkan nilai transaksi tertinggi dan apakah kategori tersebut juga merupakan kategori dengan jumlah item terjual terbanyak?
"""

print(top_10_revenue)

top_10_revenue = category_analysis.sort_values(by="total_revenue", ascending=False).head(10)
top_10_volume = category_analysis.sort_values(by="total_items_sold", ascending=False).head(10)

fig, ax = plt.subplots(nrows=1, ncols=2, figsize=(24, 10))

#Untuk total revenue
sns.barplot(
    x="total_revenue",
    y="product_category_name_english",
    data=top_10_revenue,
    palette="Oranges_r",
    ax=ax[0]
)
ax[0].set_title("10 Kategori Produk Teratas Berdasarkan Total Revenue", loc="center", fontsize=15)
ax[0].set_xlabel("Total Revenue")
ax[0].set_ylabel(None)
ax[0].tick_params(axis='y', labelsize=12)

#Untuk total items sold
sns.barplot(
    x="total_items_sold",
    y="product_category_name_english",
    data=top_10_volume,
    palette="Blues_r",
    ax=ax[1]
)
ax[1].set_title("10 Kategori Produk Teratas Berdasarkan Jumlah Item Terjual", loc="center", fontsize=15)
ax[1].set_xlabel("Total Items Sold")
ax[1].set_ylabel(None)
ax[1].tick_params(axis='y', labelsize=12)

plt.tight_layout()
plt.show()

"""Berdasarkan dari hasil visualisasi berikut didapatkan 10 kategori produk teratas. Untuk kategori health_beauty mendapatkan nilai transaksi tertinggi dengan nilai 1.258681,34, namun kategori bed_bath_table justru mendapat jumlah item terjual terbanyak yaitu 11.115 item meskipun berada di peringkat ketiga dalam nilai transaksi.

## Analisis Lanjutan (Opsional)

### RFM Analysis
"""

all_df['order_purchase_timestamp'] = pd.to_datetime(all_df['order_purchase_timestamp'])

snapshot_date = all_df['order_purchase_timestamp'].max() + pd.DateOffset(days=1)

rfm_df = all_df.groupby('customer_unique_id').agg({
    'order_purchase_timestamp': lambda x: (snapshot_date - x.max()).days,
    'order_id': 'nunique',
    'price': 'sum'
}).reset_index()

rfm_df.columns = ['customer_id', 'recency', 'frequency', 'monetary']

print("Hasil RFM Analysis")
print(rfm_df)

fig, ax = plt.subplots(nrows=1, ncols=3, figsize=(30, 10))
colors = ["#72BCD4", "#72BCD4", "#72BCD4", "#72BCD4", "#72BCD4"]

#Untuk plot recency
sns.barplot(
    x="customer_id",
    y="recency",
    data=rfm_df.sort_values(by="recency", ascending=True).head(5),
    palette=colors,
    ax=ax[0]
)
ax[0].set_title("5 Pelanggan dengan Recency Tertinggi", loc="center", fontsize=15)
ax[0].set_xlabel(None)
ax[0].set_ylabel(None)
ax[0].tick_params(axis='x', labelsize=15, rotation=45)

#Untuk plot frequency
sns.barplot(
    x="customer_id",
    y="frequency",
    data=rfm_df.sort_values(by="frequency", ascending=False).head(5),
    palette=colors,
    ax=ax[1]
)
ax[1].set_title("5 Pelanggan dengan Frequency Tertinggi", loc="center", fontsize=15)
ax[1].set_xlabel(None)
ax[1].set_ylabel(None)
ax[1].tick_params(axis='x', labelsize=15, rotation=45)

#Untuk plot monetary
sns.barplot(
    x="customer_id",
    y="monetary",
    data=rfm_df.sort_values(by="monetary", ascending=False).head(5),
    palette=colors,
    ax=ax[2]
)
ax[2].set_title("5 Pelanggan dengan Monetary Tertinggi", loc="center", fontsize=15)
ax[2].set_xlabel(None)
ax[2].set_ylabel(None)
ax[2].tick_params(axis='x', labelsize=15, rotation=45)

plt.suptitle("Analisis RFM (Recency, Frequency, Monetary) (customer_id)", fontsize=20)
plt.tight_layout()
plt.show()

"""#### Mengurutkan customer berdasarkan recency, frequency, dan monetary score"""

rfm_df['r_rank'] = rfm_df['recency'].rank(ascending=False)
rfm_df['f_rank'] = rfm_df['frequency'].rank(ascending=True)
rfm_df['m_rank'] = rfm_df['monetary'].rank(ascending=True)

rfm_df.head()

#normalisasi rank customer
rfm_df['r_rank_norm'] = (rfm_df['r_rank'] / rfm_df['r_rank'].max()) * 100
rfm_df['f_rank_norm'] = (rfm_df['f_rank'] / rfm_df['f_rank'].max()) * 100
rfm_df['m_rank_norm'] = (rfm_df['m_rank'] / rfm_df['m_rank'].max()) * 100

rfm_df.drop(columns=['r_rank', 'f_rank', 'm_rank'], inplace=True)

rfm_df.head()

#bobot: R=15%, F=28%, M=57%
rfm_df['RFM_score'] = (0.15 * rfm_df['r_rank_norm']) + (0.28 * rfm_df['f_rank_norm']) + (0.57 * rfm_df['m_rank_norm'])

#skalasi ke 1-5 dan pembulatan
rfm_df['RFM_score'] *= 0.05
rfm_df = rfm_df.round(2)

print(rfm_df[['customer_id', 'RFM_score']].head(10))

"""#### Segmentasi customer berdasarkan RFM score"""

rfm_df["customer_segment"] = np.where(
    rfm_df['RFM_score'] > 4.5, "Top customers", (np.where(
        rfm_df['RFM_score'] > 4, "High value customer",(np.where(
            rfm_df['RFM_score'] > 3, "Medium value customer", np.where(
                rfm_df['RFM_score'] > 1.6, 'Low value customers', 'lost customers'))))))

rfm_df[['customer_id', 'RFM_score', 'customer_segment']].head(20)

customer_segment_df = rfm_df.groupby(by="customer_segment", as_index=False).customer_id.nunique()
customer_segment_df

customer_segment_df['customer_segment'] = pd.Categorical(customer_segment_df['customer_segment'], [
    "lost customers", "Low value customers", "Medium value customer",
    "High value customer", "Top customers"
])

"""#### Visualisasi segmen pelanggan"""

plt.figure(figsize=(10, 6))
colors_ = ["#72BCD4", "#72BCD4", "#D3D3D3", "#D3D3D3", "#D3D3D3"]

sns.barplot(
    y="customer_segment",
    x="customer_id",
    data=customer_segment_df.sort_values(by="customer_segment", ascending=False),
    palette=colors_,
)

plt.title("Customer Segment Distribution", loc="center", fontsize=15)
plt.xlabel(None)
plt.ylabel(None)
plt.tick_params(axis='y', labelsize=12)
plt.show()

"""Berdasarkan dari hasil visualisasi tersebut, melalui metode RFM Analysis ini berhasil mengidentifikasi loyalitas dan nilai ekonomi pelanggan ke dalam lima segmen strategis mulai dari `Top customers` hingga `Lost customers`. Namun sayangnya, hasil visualisasi tersebut banyak para customers yang `Low value customers`, sehingga perlunya pengkajian lagi terkait strategi pemasaran.

## Conclusion

- Conclution pertanyaan 1 : Performa bisnis menunjukkan pertumbuhan yang baik dengan puncak transaksi tertinggi terjadi pada bulan November tahun 2017. Tren ini secara keseluruhan menunjukkan korelasi positif antara banyaknya pesanan dan total pendapatan perusahaan.

- Conclution pertanyaan 2 : Pada kategori security_and_service diidentifikasi memiliki tingkat kepuasan terendah dengan skor rata-rata 2,5 yang jauh dibawah standar kategori lainnya. Hal ini perlu adanya audit lebih lagi pada kualitas produk serta efisiensi pengiriman khususnya kategori tersebut guna meningkatkan tingkat kepuasan pelanggan.

- Conclution pertanyaan 3 : Negara bagian Sao Paulo (SP) menjadi basis pasar utama dengan jumlah pelanggan mencapai 39.981 orang dan berkontribusi sebesar 38,28% terhadap total pendapatan. Hal ini didasari oleh strategi operasional dan logistik perusahaan yang baik di pusat ekonomi utama tersebut.

- Conclution pertanyaan 4 : Performa produk terdapat perbedaan karakteristik antara produk yang paling menguntungkan dan juga yang paling laku, yang dimana health_beauty menduduki total pendapatan terbanyak, sedangkan bed_bath_table menduduki total jumlah unit terjual yang terbanyak. Mungkin dengan strategi stok barang dan pemasaran harus lebih disesuaikan dengan profil masing-masing kategori guna meningkatkan performa produk.

- Conclution (RFM Analysis untuk segmentasi pelanggan) : Melalui metode RFM Analysis ini berhasil memetakan profil pelanggan ke dalam lima segmen mulai dari Top hingga Lost Customers berdasarkan perilaku dari belanja mereka. Hal ini dapat memungkinkan perusahaan dalam menjalankan strategi pemasaran yang lebih personal, seperti memberikan apresiasi pada segmen Top dan melakukan re-aktivasi pengenalan atau penjelasan produk yang rapi bagi pelanggan di segmen bawah.
"""

# # Codingan Dashboard Streamlit
# import pandas as pd
# import matplotlib.pyplot as plt
# import seaborn as sns
# import streamlit as st
# from babel.numbers import format_currency

# sns.set(style='dark')

# # 1. Helper Functions
# def create_daily_orders_df(df):
#     daily_orders_df = df.resample(rule='D', on='order_purchase_timestamp').agg({
#         "order_id": "nunique",
#         "price": "sum"
#     }).reset_index()
#     daily_orders_df.rename(columns={
#         "order_id": "order_count",
#         "price": "revenue"
#     }, inplace=True)
#     return daily_orders_df

# def create_bycategory_review_df(df):
#     category_review_df = df.groupby("product_category_name_english").review_score.mean().sort_values(ascending=True).reset_index()
#     return category_review_df

# def create_bystate_df(df):
#     bystate_df = df.groupby(by="customer_state").customer_unique_id.nunique().reset_index()
#     bystate_df.rename(columns={
#         "customer_unique_id": "customer_count"
#     }, inplace=True)
#     return bystate_df

# def create_product_performance_df(df):
#     product_performance_df = df.groupby("product_category_name_english").agg({
#         "order_id": "nunique",
#         "price": "sum"
#     }).reset_index()
#     product_performance_df.rename(columns={
#         "order_id": "quantity",
#         "price": "revenue"
#     }, inplace=True)
#     return product_performance_df

# def create_rfm_df(df):
#     snapshot_date = df['order_purchase_timestamp'].max() + pd.DateOffset(days=1)
#     rfm_df = df.groupby('customer_unique_id').agg({
#         'order_purchase_timestamp': lambda x: (snapshot_date - x.max()).days,
#         'order_id': 'nunique',
#         'price': 'sum'
#     }).reset_index()
#     rfm_df.columns = ['customer_id', 'recency', 'frequency', 'monetary']

#     rfm_df['r_rank'] = rfm_df['recency'].rank(ascending=False)
#     rfm_df['f_rank'] = rfm_df['frequency'].rank(ascending=True)
#     rfm_df['m_rank'] = rfm_df['monetary'].rank(ascending=True)

#     rfm_df['RFM_score'] = (0.15 * (rfm_df['r_rank']/rfm_df['r_rank'].max())*100) + \
#                           (0.28 * (rfm_df['f_rank']/rfm_df['f_rank'].max())*100) + \
#                           (0.57 * (rfm_df['m_rank']/rfm_df['m_rank'].max())*100)
#     rfm_df['RFM_score'] *= 0.05
#     rfm_df = rfm_df.round(2)
#     return rfm_df

# # 2. Load Data
# all_df = pd.read_csv("all_data.csv")

# datetime_columns = ["order_purchase_timestamp"]
# for column in datetime_columns:
#     all_df[column] = pd.to_datetime(all_df[column])

# all_df.sort_values(by="order_purchase_timestamp", inplace=True)
# all_df.reset_index(inplace=True)

# # 3. Sidebar Filter
# min_date = all_df["order_purchase_timestamp"].min()
# max_date = all_df["order_purchase_timestamp"].max()

# with st.sidebar:
#     st.title("E-Commerce Dashboard")
#     # Ganti URL logo jika perlu
#     st.image("https://github.com/dicodingacademy/assets/raw/main/logo.png")

#     start_date, end_date = st.date_input(
#         label='Rentang Waktu',
#         min_value=min_date,
#         max_value=max_date,
#         value=[min_date, max_date]
#     )
# main_df = all_df[(all_df["order_purchase_timestamp"] >= str(start_date)) &
#                  (all_df["order_purchase_timestamp"] <= str(end_date))]

# daily_orders_df = create_daily_orders_df(main_df)
# category_review_df = create_bycategory_review_df(main_df)
# bystate_df = create_bystate_df(main_df)
# product_performance_df = create_product_performance_df(main_df)
# rfm_df = create_rfm_df(main_df)

# # 4. Main Dashboard
# st.header('E-Commerce Performance Dashboard :sparkles:')

# # Pertanyaan 1
# st.subheader('Daily Orders & Revenue')
# col1, col2 = st.columns(2)
# with col1:
#     st.metric("Total Orders", value=daily_orders_df.order_count.sum())
# with col2:
#     total_rev = format_currency(daily_orders_df.revenue.sum(), "BRL", locale='pt_BR')
#     st.metric("Total Revenue", value=total_rev)

# fig, ax = plt.subplots(figsize=(16, 8))
# ax.plot(daily_orders_df["order_purchase_timestamp"], daily_orders_df["order_count"], marker='o', linewidth=2, color="#90CAF9")
# st.pyplot(fig)

# # Pertanyaan 2 dan 4
# st.subheader("Product Category Performance")
# tab1, tab2 = st.tabs(["Review Score", "Sales Performance"])

# with tab1:
#     st.write("Kategori dengan Kepuasan Terendah")
#     fig, ax = plt.subplots(figsize=(12, 6))
#     sns.barplot(x="review_score", y="product_category_name_english", data=category_review_df.head(10), palette="Reds_r")
#     st.pyplot(fig)

# with tab2:
#     col1, col2 = st.columns(2)
#     with col1:
#         st.write("Top 5 by Revenue")
#         fig, ax = plt.subplots(figsize=(10, 5))
#         sns.barplot(x="revenue", y="product_category_name_english", data=product_perf_df.sort_values("revenue", ascending=False).head(5), palette="Blues_r")
#         st.pyplot(fig)
#     with col2:
#         st.write("Top 5 by Quantity")
#         fig, ax = plt.subplots(figsize=(10, 5))
#         sns.barplot(x="quantity", y="product_category_name_english", data=product_perf_df.sort_values("quantity", ascending=False).head(5), palette="GnBu_r")
#         st.pyplot(fig)

# # Pertanyaan 3
# st.subheader("Customer Geographics")
# fig, ax = plt.subplots(figsize=(12, 6))
# sns.barplot(x="customer_count", y="customer_state", data=bystate_df.sort_values("customer_count", ascending=False).head(10), palette="viridis")
# st.pyplot(fig)

# # RFM Analysis
# st.subheader("Best Customer Based on RFM Parameters")
# col1, col2, col3 = st.columns(3)
# with col1:
#     st.metric("Avg Recency (days)", value=round(rfm_df.recency.mean(), 1))
# with col2:
#     st.metric("Avg Frequency", value=round(rfm_df.frequency.mean(), 2))
# with col3:
#     st.metric("Avg Monetary", value=format_currency(rfm_df.monetary.mean(), "BRL", locale='pt_BR'))

# # Visualisasi Top 5 Customers per RFM
# fig, ax = plt.subplots(nrows=1, ncols=3, figsize=(30, 10))
# sns.barplot(y="recency", x="customer_id", data=rfm_df.sort_values("recency", ascending=True).head(5), ax=ax[0])
# ax[0].set_title("By Recency", fontsize=30)
# sns.barplot(y="frequency", x="customer_id", data=rfm_df.sort_values("frequency", ascending=False).head(5), ax=ax[1])
# ax[1].set_title("By Frequency", fontsize=30)
# sns.barplot(y="monetary", x="customer_id", data=rfm_df.sort_values("monetary", ascending=False).head(5), ax=ax[2])
# ax[2].set_title("By Monetary", fontsize=30)
# st.pyplot(fig)

# st.caption('Copyright © Nurya Dashboard 2026')

